### ISSUE TITLE
Settings.conf appears to be placed in the wrong directory

### ISSUE THREAD

**Issue by ctnlaring** [lirios/calamares-branding#1]
On my system building puts settings.conf in /usr/local/etc/calamares/ but it's supposed to be in one of two other places according to my calamares crash log:

10:57:13 [0]: FATAL ERROR: none of the expected configuration file paths ( "/etc/calamares/settings.conf, /usr/share/calamares/settings.conf" ) contain a valid settings.conf file. 
Cowardly refusing to continue startup without settings. 

Is there something weird about my install or has the location changed?

**Comment by ctnlaring** [comment]
Would be fixed in #2 if I did that correctly

**Comment by plfiorini** [comment]
Seems like a cmake configuration issue you didn't pass the correct arguments.
Closing the issue.
