### ISSUE TITLE
Evaluate forking Calamares (or another installer)

### ISSUE THREAD

**Issue by ctnlaring** [lirios/calamares-branding#4]
Little things like logos and text can be changed but calamares branding doesn't give enough control to get anywhere near material. Much more could be done by forking the whole thing.

**Comment by ctnlaring** [comment]
I've started a test here: [liri-installer.](https://github.com/Collinthegeek/Liri-Installer) So far it's just a merge of calamares with liri-branding but I'll start tweaking the UI and see if I can make it more material

**Comment by plfiorini** [comment]
Yeah Calamares still uses the old and ugly QtWidgets, if it was using QtQuick Controls 2 we could at least get the material style without effort.

That said the work behind an installer is huge and at least Calamares is maintained by a cross-distro community and can give us something that works without consuming our time.

The fork should move Calamares to QtQuick Controls 2 so it can eventually be merged upstream. You can ask teo- (the maintainer) on IRC #calamares

**Comment by ctnlaring** [comment]
Alright. I'm doing little things like changing icons but don't have the knowledge to do an overhaul like that.

**Comment by plfiorini** [comment]
Ok in that case you can make a Qt stylesheet, sounds like a good compromise between the overhaul and a good result.

http://doc.qt.io/qt-5/stylesheet-reference.html

Usually Qt widgets apps can be launched with -stylesheet something like:

```calamares -stylesheet mystyle.css```

**Comment by ctnlaring** [comment]
That looks more doable. I'll work for a while and let you know

**Comment by ctnlaring** [comment]
This appears to be working, made some flat buttons

**Comment by Collinthegeek** [comment]
Is there a specific MD palette I should be using? 

https://material.io/color/#!/?view.left=0&view.right=0&primary.color=607D8B?

**Comment by Collinthegeek** [comment]
@plfiorini  I could use some design guidance. I'm having difficulty with shadows as my only css experience is for the web. Currently I've got buttons that mostly follow the material guidelines for [dialog boxes](https://material.io/guidelines/components/dialogs.html#dialogs-specs) (The font isn't done) but I'm not sure if that's technically proper. I'm worried about consistency trying to make this match fluid. If you or somebody has design ideas/mockups they'd be appreciated. 

![screenshot from 2017-04-16 17-00-23](https://cloud.githubusercontent.com/assets/2424846/25074346/ba7daadc-22c6-11e7-9bf8-1fde9aa23e0a.png)

**Comment by ctnlaring** [comment]
This no longer appears to be working, I've been working all day and with QT's weird alien CSS and the complex module system of Calamares I've barely made any progress. Qt stylsheets can't do animation and there's tons of stuff that would probably just be better to overhaul it with quick controls or do something else entirely. Someone with more knowledge who has the skills for an overhaul should do it but It's not really a priority. Since It's already not material you could consider switching to arch-anywhere so you don't have to worry about the crashes you're currently getting with the xorg dependency of Calamares

**Comment by ctnlaring** [comment]
https://github.com/deadhead420/arch-linux-anywhere

**Comment by plfiorini** [comment]
It doesn't seem to have a graphical installer though.

**Comment by ctnlaring** [comment]
Yes that's my point. I mean just as a temporary replacement for calamares since it's so buggy

**Comment by ctnlaring** [comment]
Sorry for bumping an old thread but I've started working on a gtk installer.
[http://collinnorwood.com/akita/](http://collinnorwood.com/akita/)
It's nowhere near ready but it almost works right now.

**Comment by plfiorini** [comment]
Ok when it's ready to be compared to Calamares I will take a look.
Meanwhile I'm closing the issue.
